name: Deploy
on:
  push:
    branches:
      - main
    paths:
      - .github/**
      - src/**
      - index.html

jobs:
  test:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - run: |
          yarn
          yarn jest

  typecheck:
    name: Typescript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - run: |
          yarn
          yarn tsc --noEmit

  deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    needs: 
      - test
      - typecheck
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Build
        run: |
          yarn
          yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
